### ISSUE TITLE
使用 custom 上传失败

### ISSUE THREAD

**Issue by MoChengYao** [zhuxining/obsidian-attachment-uploader#10]
现在在设置里面执行上传测试是正常的，但是在外边上传的时候，会提示未找到符合上传条件的本地附件，求一个详细一点 custom 上传的说明文档

<img width="1240" alt="image" src="https://github.com/user-attachments/assets/0c65907d-aa6b-4129-82ce-e065a3280053">

<img width="1344" alt="image" src="https://github.com/user-attachments/assets/0105b8c6-221d-499d-bb1e-f6245d29d10d">

**Comment by gaozelle** [comment]
custom设置好后关闭设置，会自动清除写进去的参数，打开后是空的。另外用默认的upic设置，我这里上传失败。麻烦测试一下！

**Comment by zhuxining** [comment]
3. 自定义命令示例
    - uPic在shell中的执行命令为`/Applications/uPic.app/Contents/MacOS/uPic -o url -u /local.png`
    - shell中输出为
        ```
        Uploading ...
        Uploading 1/1
        Output URL:
        https://r-w.oss-cn-shanghai.aliyuncs.com/uPic/Snipaste_2024-08-18_22-14-14.png?x-oss-process=image/auto-orient,1/quality,q_80/format,webp
        ```
    - 此插件用%s代替图片本地地址，通过`urlMatch = stdout.match(/s+(https?:/ / S +) /)`来提取命令执行后shell中输出的图片url
    - 因此使用uPic命令为`/Applications/uPic.app/Contents/MacOS/uPic -o url -u %s`
    - 如果自己写脚本来上传图片,请在shell输出中打印上传后的图片网络地址
@gaozelle @MoChengYao
