### ISSUE TITLE
Custom自定义方式的上传文件命令不会保存

### ISSUE THREAD

**Issue by 4ch12dy** [zhuxining/obsidian-attachment-uploader#8]
使用Custom上传文件的时候，输入命令后，现场测试可以，但退出界面再次进入就会空，应该是没有保存之前的命令

**Comment by 4ch12dy** [comment]
我目前是直接修改main.js在里面写死了，但不是很优雅

**Comment by 4ch12dy** [comment]
另外希望作者增加一个功能，如果不是图片的时候，不使用
```
![](http://example.png)
```
而是使用
```
[example.zip](http://a.com/example.zip)
```
example.zip是原始文件的basename

**Comment by zhuxining** [comment]
没有理解你的意思，现在的逻辑是：
1. 查找出所有 markdown 的![]()格式，
2. 提取附件文件的文件类型（就是文件格式后缀），
3. 判断文件格式后缀在 settings 格式列表的，上传，不在列表的忽略。 @4ch12dy

**Comment by zhuxining** [comment]
不知道理解的对不对，增加了一个判断：
如果文件后缀格式在 obsidian 支持的 Image files 中，则用`![]()`替换，不是图片的则用`[]()`替换
https://help.obsidian.md/Files+and+folders/Accepted+file+formats

```
const isImage = /\.(avif|bmp|gif|jpeg|jpg|png|svg|webp)$/i.test(attachment.ext);
const updatedContent = content.replace(
	attachment.source,
	isImage ? `![${attachment.name}](${encodeURI(newUrl)})` : `[${attachment.name}](${encodeURI(newUrl)})`
);
editor.editor?.setValue(updatedContent);
```
PS:我也是新手，就会点Python，1.0是看着别人的代码跟着写，后面的版本都是丢到chatGPT里让重构优化的。
